### ISSUE TITLE
lack of knowledge

### ISSUE THREAD

**Issue by MoonWooJohn** [MazinCE/RVCOM2.0#1]
Beow ones , how to do it?  I am sorry that I would have lack of knowledge for " RISC-V C/C++ compiler" . Please give me some more detailed information ? For demo, I followed your instrcuction, I could do it, but below ones I don't have any idea what I do. 
Thank for your data and other information which I could understand RISC V a little more. 
"You'll need a RISC-V C/C++ compiler, I personaly use this one for my windows machine https://gnutoolchains.com/risc-v/
Load the generated binary file into the first bank in the memory module.
Tested in Logisim-evolution v3.7.2"

**Comment by Mazin-O3** [comment]
Hi, Thanks for pointing this out,
I'll include a starter project template to write code directly.

**Comment by MoonWooJohn** [comment]
Thank you  very much for your kindess...   I anks again
