### ISSUE TITLE
load the generated binary file

### ISSUE THREAD

**Issue by MoonWooJohn** [MazinCE/RVCOM2.0#2]
Thank you very much for your data and all information !!!!
But it would be complicated because  lack of knowledge....
"Load the generated binary file into the first bank in the memory module."  Would you pls give me which bin files should be loaded ?
my folder "C:\SysGCC\risc-v\bin" has many kinds of files? But I would not know which one? 
pls help me ?

**Comment by Mazin-O3** [comment]
A project template is now included you can find it in projects/template project

**Comment by MoonWooJohn** [comment]
Hi ! Mr. Mazin Mohammed

Thank you for your kindness very much ....
I will try it and thanks again.

Very truly yours


2022년 12월 12일 (월) 오후 9:42, Mazin Mohammed ***@***.***>님이 작성:
